CREATE TABLE ADDRESS (
    ADDRESS_ID NUMBER NOT NULL,
    ADDRESS_NUMBER NUMBER,
    ADDRESS_STREET VARCHAR2(255),
    ADDRESS_CITY VARCHAR2(255),
    ADDRESS_REGION VARCHAR2(255),
    ADDRESS_ZIPCODE VARCHAR2(10),
    CONSTRAINT pk_address_id PRIMARY KEY (ADDRESS_ID)
);
CREATE TABLE ACCESSTABLE (
    ACCESS_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    ACCESS_CANENROLLPATIENT CHAR(1),
    ACCESS_CANEDITPATIENTINFO CHAR(1),
    ACCESS_CANVIEWPATIENTINFO CHAR(1),
    ACCESS_CANDELETEUSER CHAR(1),
    ACCESS_CANDELETEPATIENTINFO CHAR(1),
    CONSTRAINT pk_access_id PRIMARY KEY (ACCESS_ID)
);

CREATE TABLE ROLE (
    ROLE_ID NUMBER NOT NULL,
    ROLE_NAME VARCHAR2(255),
    ROLE_DESCRIPTION VARCHAR2(1000),
    CONSTRAINT pk_role_id PRIMARY KEY (ROLE_ID)
);


CREATE TABLE HOSPITAL (
    HOSPITAL_ID NUMBER NOT NULL,
    HOSPITAL_NAME VARCHAR2(255),
    HOSPITAL_ADDRESS NUMBER,
    HOSPITAL_CONTACT_NO VARCHAR2(15),
    CONSTRAINT pk_hospital_id PRIMARY KEY (HOSPITAL_ID),
    CONSTRAINT fk_address_hospital FOREIGN KEY (HOSPITAL_ADDRESS) REFERENCES Address(ADDRESS_ID)
);

CREATE TABLE DEPARTMENT (
    DEPARTMENT_ID NUMBER NOT NULL,
    DEPARTMENT_NAME VARCHAR2(255),
    CONSTRAINT pk_department_id PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE SPECIALTY (
    SPECIALTY_ID NUMBER NOT NULL,
    SPECIALTY_NAME VARCHAR2(255),
    SPECIALTY_DESCRIPTION VARCHAR2(1000),
    CONSTRAINT pk_specialty_id PRIMARY KEY (SPECIALTY_ID)
);
CREATE TABLE USERTABLE (
    USER_ID NUMBER NOT NULL,
    USER_LASTNAME VARCHAR2(255) NOT NULL,
    USER_FIRSTNAME VARCHAR2(255) NOT NULL,
    USER_MIDDLENAME VARCHAR2(255),
    USER_EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    USER_PASSWORD VARCHAR2(255) NOT NULL,
    USER_GENDER VARCHAR2(50) NOT NULL,
    USER_MARITAL_STATUS VARCHAR2(50) NOT NULL,
    USER_BIRTHDATE DATE NOT NULL,
    USER_BIRTHPLACE VARCHAR2(255) NOT NULL,
    USER_ADDRESS NUMBER, -- Foreign key to Address table
    USER_ROLE NUMBER, -- Foreign key to a Role table
    USER_ACCESS NUMBER , -- Foreign key to an Access table
    USER_IS_VERIFIED CHAR(1),
    USER_STATUS VARCHAR2(50),
    USER_CREATED_ON TIMESTAMP,
    USER_UPDATED_ON TIMESTAMP,
    USER_ENCODER NUMBER NOT NULL, -- Foreign key to another User or another table
    CONSTRAINT pk_user_id PRIMARY KEY (USER_ID),
    CONSTRAINT fk_address_user FOREIGN KEY (USER_ADDRESS) REFERENCES Address(ADDRESS_ID),
    CONSTRAINT fk_role_user FOREIGN KEY (USER_ROLE) REFERENCES Role(role_ID),
    CONSTRAINT fk_access_user FOREIGN KEY (USER_ACCESS) REFERENCES ACCESSTABLE(access_ID),
    CONSTRAINT fk_encoder_user FOREIGN KEY (USER_ENCODER) REFERENCES USERTABLE(user_id)
);

ALTER TABLE ACCESSTABLE ADD CONSTRAINT fk_user_access FOREIGN KEY (USER_ID) REFERENCES USERTABLE(USER_ID);

CREATE TABLE PATIENT (
    PATIENT_ID NUMBER NOT NULL,
    USER_ID NUMBER,
    PATIENT_DISEASE NUMBER, -- Foreign key to a Disease table (SAKA NA LANG LAGYAN NG NOT NULL PAG MAY DISEASE TABLE NA)
    PATIENT_SURGERY NUMBER, -- Foreign key to a Surgery table
    PATIENT_CHEMOTHERAPY NUMBER, -- Foreign key to a Chemotherapy table
    PATIENT_RADIOTHERAPY NUMBER, -- Foreign key to a Radiotherapy table
    PATIENT_IMMUNOTHERAPY NUMBER, -- Foreign key to an Immunotherapy table
    PATIENT_HORMONAL_RX NUMBER, -- Foreign key to a HormonalRx table
    PATIENT_CREATED_ON TIMESTAMP,
    PATIENT_UPDATED_ON TIMESTAMP,
    CONSTRAINT pk_patient_id PRIMARY KEY (PATIENT_ID),
    CONSTRAINT fk_user_patient FOREIGN KEY (user_ID) REFERENCES USERTABLE(user_id)--,
    --CONSTRAINT fk_disease FOREIGN KEY (PATIENT_DISEASE) REFERENCES Disease(disease_ID),
    --CONSTRAINT fk_surgery FOREIGN KEY (PATIENT_SURGERY) REFERENCES Surgery(surgery_ID),
    --CONSTRAINT fk_chemotherapy FOREIGN KEY (PATIENT_CHEMOTHERAPY) REFERENCES Chemotherapy(chemotherapy_ID),
    --CONSTRAINT fk_radiotherapy FOREIGN KEY (PATIENT_RADIOTHERAPY) REFERENCES Radiotherapy(radiotherapy_ID),
    --CONSTRAINT fk_immunotherapy FOREIGN KEY (PATIENT_IMMUNOTHERAPY) REFERENCES Immunotherapy(immunotherapy_ID),
    --CONSTRAINT fk_hormonalrx FOREIGN KEY (PATIENT_HORMONAL_RX) REFERENCES HormonalRx(hormonalrx_ID)
);

CREATE TABLE DOCTOR (
    DOCTOR_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    DOCTOR_HOSPITAL NUMBER NOT NULL, -- Foreign key to a Hospital table
    DOCTOR_DEPARTMENT NUMBER NOT NULL, -- Foreign key to a Department table
    DOCTOR_SPECIALTY NUMBER NOT NULL, -- Foreign key to a Specialty table
    DOCTOR_E_SIGNATURE BLOB,
    DOCTOR_LICENSE_NUMBER VARCHAR2(8) NOT NULL,
    DOCTOR_LICENSE_EXP_DATE DATE NOT NULL,
    DOCTOR_SCHEDULE NUMBER NOT NULL, -- Foreign key to a Schedule table
    CONSTRAINT pk_doctor_id PRIMARY KEY (DOCTOR_ID),
    CONSTRAINT fk_user_doctor FOREIGN KEY (user_ID) REFERENCES USERTABLE(user_id),
    CONSTRAINT fk_hospital_doctor FOREIGN KEY (DOCTOR_HOSPITAL) REFERENCES Hospital(hospital_ID),
    CONSTRAINT fk_department_doctor FOREIGN KEY (DOCTOR_DEPARTMENT) REFERENCES Department(department_ID),
    CONSTRAINT fk_specialty_doctor FOREIGN KEY (DOCTOR_SPECIALTY) REFERENCES Specialty(specialty_ID)--,
    --CONSTRAINT fk_schedule_doctor FOREIGN KEY (DOCTOR_SCHEDULE) REFERENCES Schedule(schedule_ID)
);

CREATE TABLE ONBOARD (
    RELATION_ID NUMBER NOT NULL,
    PATIENT_ID NUMBER NOT NULL,
    DOCTOR_ID NUMBER NOT NULL,
    DOCTOR_ROLE VARCHAR2(255),
    CONSTRAINT pk_relation_id PRIMARY KEY (RELATION_ID),
    CONSTRAINT fk_patient_onboard FOREIGN KEY (patient_ID) REFERENCES Patient(patient_ID),
    CONSTRAINT fk_doctor_onboard FOREIGN KEY (doctor_ID) REFERENCES Doctor(doctor_ID)
);

CREATE SEQUENCE ADDRESS_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE ACCESS_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE ROLE_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE HOSPITAL_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE DEPARTMENT_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE SPECIALTY_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE USER_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE PATIENT_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE DOCTOR_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE ONBOARD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

alter table ACCESSTABLE drop constraint FK_USER_ACCESS;
alter table ACCESSTABLE drop column USER_ID;